import mcdonaldsJapanFoods from '../data/mcdonalds_japan.json' with { type: 'json' }
import starbucksJapanFoods from '../data/starbucks_japan.json' with { type: 'json' }
import lotteJapanFoods from '../data/lotte_japan.json' with { type: 'json' }
import meijiJapanFoods from '../data/meiji_japan.json' with { type: 'json' }
import manualFoods from '../data/food.json' with { type: 'json' }
import convenienceStoreJapanFoods from '../data/convenience_store_japan.json' with { type: 'json' }

export type Nutrition = {
  calories: number
  protein: number
  fat: number
  carbohydrates: number
}

// Optional finer-grained nutrients, not part of core totals/targets. Present
// when the source publishes them (e.g. Starbucks Japan's nutrition table).
export type NutritionDetail = {
  salt?: number
  fiber?: number
  sugar?: number
  sodium?: number
  potassium?: number
  transFat?: number
  saturatedFat?: number
  caffeine?: number
  cholesterol?: number
}

export type Profile = {
  age: number
  sex: 'female' | 'male'
  heightCm: number
  weightKg: number
  activity: 'bmrOnly' | 'sedentary' | 'light' | 'moderate' | 'very' | 'extra'
  targetWeightKg: number
  targetDate: string
}

export type TargetOverrides = Partial<Nutrition>

export type TargetPeriod = {
  effectiveFrom: string
  targets: Nutrition
}

export type Food = {
  id: string
  name: Record<string, string>
  // Optional free-text detail (e.g. brand name) shown alongside the food's
  // name in lists and search results. Absent on data saved before this field
  // existed; treated as "no description" everywhere.
  description?: string
  serving: string
  nutrition: Nutrition
  // Optional finer-grained nutrients beyond the core Nutrition totals.
  detail?: NutritionDetail
  source: 'bundled' | 'user'
  // ISO timestamp of creation/last edit. Absent on data saved before this
  // field existed or on bundled foods; used to sort the custom foods list by
  // most recently updated first.
  updatedAt?: string
}

export type MealEntry = {
  id: string
  date: string
  time: string
  foodId: string
  foodName?: string
  quantity: number
  nutrition: Nutrition
}

export type AchievementId =
  | 'ready-set'
  | 'first-plate'
  | 'tenfold-log'
  | 'fifty-plates'
  | 'hundred-plates'
  | 'quick-start'
  | 'three-day-start'
  | 'week-witness'
  | 'monthly-companion'
  | 'hundred-day-journal'
  | 'steady-starter'
  | 'seven-day-rhythm'
  | 'two-week-pace'
  | 'monthly-rhythm'
  | 'familiar-favorite'
  | 'regular'
  | 'signature-order'
  | 'ten-tastes'
  | 'twenty-five-tastes'
  | 'fifty-tastes'
  | 'first-custom-food'
  | 'personal-pantry'

export type AchievementRecord = {
  id: AchievementId
  unlockedAt: string
  readAt?: string
}

export type AppData = {
  foods: Food[]
  mealEntries: MealEntry[]
  exerciseCalories?: Record<string, number>
  profile?: Profile
  targetOverrides?: TargetOverrides
  targetPeriods?: TargetPeriod[]
  achievements?: AchievementRecord[]
  // Favorited food ids. Kept separate from Food records (rather than a
  // `favorite` flag on Food) because bundled foods are wholesale replaced
  // from their canonical source on every load — a flag there would be wiped.
  favoriteFoodIds?: string[]
}

export type Backup = {
  schemaVersion: 1
  exportedAt: string
  data: AppData
}

export type ImportResult = {
  schemaVersion: 1
  data: AppData
}

export type Store = {
  load(): Promise<AppData>
  save(data: AppData): Promise<void>
  export(): Promise<string>
  import(file: string): Promise<ImportResult>
}

type AchievementDefinition = {
  id: AchievementId
  titleKey: string
  ruleKey: string
  badgeNumber: string
  badgeIcon: 'crown' | 'star'
  qualifies: (data: AppData, stats: AchievementStats) => boolean
}

// mcdonaldsJapanFoods is generated by scripts/import_mcdonalds_japan.py from
// McDonald's Japan's official nutrition table and English product pages; do
// not hand-edit, re-run the importer instead.
// starbucksJapanFoods is hand-curated from Starbucks Japan's official
// per-drink nutrition calculator at menu.starbucks.co.jp (JS-driven, not
// scriptable); each entry's serving records the size/temperature shown.
// lotteJapanFoods is generated by scripts/import_lotte_japan.py from Lotte
// Japan's official ice cream ("アイス") product catalogue; do not hand-edit,
// re-run the importer instead. Lotte does not publish official English or
// Chinese names, so only the Japanese name is recorded.
// meijiJapanFoods is generated by scripts/import_meiji_japan.py from Meiji
// Japan's official ice cream ("アイス") product catalogue; do not hand-edit,
// re-run the importer instead. Meiji does not publish official English or
// Chinese names, so only the Japanese name is recorded.
// manualFoods is hand-curated (not scraped) in web/src/data/food.json for
// bundled foods not covered by an importer; edit that file directly.
export const bundledFoods: Food[] = [
  ...(mcdonaldsJapanFoods as Food[]),
  ...(starbucksJapanFoods as Food[]),
  ...(lotteJapanFoods as Food[]),
  ...(meijiJapanFoods as Food[]),
  ...(manualFoods as Food[]),
  ...(convenienceStoreJapanFoods as Food[]),
]

const SCHEMA_VERSION = 1 as const
// ponytail: JSON round-trip instead of structuredClone — the latter throws on
// Svelte 5 $state proxies passed in by callers; JSON.stringify unwraps them
// via normal property access. Fine since AppData is plain JSON-safe data.
const copy = <T>(value: T): T => JSON.parse(JSON.stringify(value))
const emptyData = (): AppData => ({ foods: [], mealEntries: [] })
const achievementIds = new Set<AchievementId>([
  'ready-set',
  'first-plate',
  'tenfold-log',
  'fifty-plates',
  'hundred-plates',
  'quick-start',
  'three-day-start',
  'week-witness',
  'monthly-companion',
  'hundred-day-journal',
  'steady-starter',
  'seven-day-rhythm',
  'two-week-pace',
  'monthly-rhythm',
  'familiar-favorite',
  'regular',
  'signature-order',
  'ten-tastes',
  'twenty-five-tastes',
  'fifty-tastes',
  'first-custom-food',
  'personal-pantry',
])

function invalid(message: string): never {
  throw new Error(`Invalid data: ${message}`)
}

function validNutrition(value: unknown): value is Nutrition {
  return (
    typeof value === 'object' &&
    value !== null &&
    ['calories', 'protein', 'fat', 'carbohydrates'].every((key) => {
      const number = (value as Record<string, unknown>)[key]
      return typeof number === 'number' && Number.isFinite(number) && number >= 0
    })
  )
}

function validateAchievementRecord(record: unknown): asserts record is AchievementRecord {
  if (typeof record !== 'object' || record === null) invalid('achievement')
  const value = record as Record<string, unknown>
  if (
    typeof value.id !== 'string' ||
    !achievementIds.has(value.id as AchievementId) ||
    typeof value.unlockedAt !== 'string' ||
    !value.unlockedAt ||
    (value.readAt !== undefined && (typeof value.readAt !== 'string' || !value.readAt))
  )
    invalid('achievement')
}

function validateTargetPeriod(period: unknown): asserts period is TargetPeriod {
  if (typeof period !== 'object' || period === null) invalid('target period')
  const value = period as Record<string, unknown>
  if (typeof value.effectiveFrom !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value.effectiveFrom) || !validNutrition(value.targets))
    invalid('target period')
}

export function validateFood(food: unknown): asserts food is Food {
  if (typeof food !== 'object' || food === null) invalid('food')
  const value = food as Record<string, unknown>
  const names = value.name
  if (
    typeof value.id !== 'string' ||
    !value.id ||
    typeof names !== 'object' ||
    names === null ||
    !Object.values(names).some((name) => typeof name === 'string' && name.trim()) ||
    typeof value.serving !== 'string' ||
    !value.serving.trim() ||
    !validNutrition(value.nutrition) ||
    (value.source !== 'bundled' && value.source !== 'user') ||
    (value.description !== undefined && typeof value.description !== 'string') ||
    (value.updatedAt !== undefined && typeof value.updatedAt !== 'string')
  )
    invalid('food')
}

export function validateMealEntry(entry: unknown, foods: Food[]): asserts entry is MealEntry {
  if (typeof entry !== 'object' || entry === null) invalid('meal entry')
  const value = entry as Record<string, unknown>
  if (
    typeof value.id !== 'string' ||
    !value.id ||
    !/^\d{4}-\d{2}-\d{2}$/.test(String(value.date)) ||
    !/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(String(value.time)) ||
    typeof value.foodId !== 'string' ||
    typeof value.quantity !== 'number' ||
    !Number.isFinite(value.quantity) ||
    value.quantity <= 0 ||
    !validNutrition(value.nutrition) ||
    (value.foodId === '' && (typeof value.foodName !== 'string' || !value.foodName.trim()))
  )
    invalid('meal entry')
}

export function validateAppData(data: unknown): asserts data is AppData {
  if (typeof data !== 'object' || data === null) invalid('application data')
  const value = data as Record<string, unknown>
  if (!Array.isArray(value.foods) || !Array.isArray(value.mealEntries)) invalid('application data')
  value.foods.forEach(validateFood)
  value.mealEntries.forEach((entry) => validateMealEntry(entry, value.foods as Food[]))
  if (
    value.exerciseCalories !== undefined &&
    (typeof value.exerciseCalories !== 'object' ||
      value.exerciseCalories === null ||
      Array.isArray(value.exerciseCalories) ||
      !Object.entries(value.exerciseCalories).every(
        ([date, calories]) => /^\d{4}-\d{2}-\d{2}$/.test(date) && typeof calories === 'number' && Number.isFinite(calories) && calories >= 0,
      ))
  )
    invalid('exercise calories')
  if (value.profile !== undefined) validateProfile(value.profile)
  if (value.targetOverrides !== undefined) validateTargetOverrides(value.targetOverrides)
  if (value.targetPeriods !== undefined) {
    if (!Array.isArray(value.targetPeriods)) invalid('target periods')
    value.targetPeriods.forEach(validateTargetPeriod)
    if (new Set(value.targetPeriods.map((period) => (period as TargetPeriod).effectiveFrom)).size !== value.targetPeriods.length)
      invalid('target period')
  }
  if (value.achievements !== undefined) {
    if (!Array.isArray(value.achievements)) invalid('application data')
    value.achievements.forEach(validateAchievementRecord)
    if (new Set(value.achievements.map((record) => (record as AchievementRecord).id)).size !== value.achievements.length)
      invalid('achievement')
  }
  if (
    value.favoriteFoodIds !== undefined &&
    (!Array.isArray(value.favoriteFoodIds) || !value.favoriteFoodIds.every((id) => typeof id === 'string' && id))
  )
    invalid('favorite food ids')
}

export function createFood(input: Omit<Food, 'id'> & { id?: string }): Food {
  const food = { ...input, id: input.id ?? crypto.randomUUID(), updatedAt: input.updatedAt ?? new Date().toISOString() }
  validateFood(food)
  return copy(food)
}

export function scaleNutrition(nutrition: Nutrition, quantity: number): Nutrition {
  if (!Number.isFinite(quantity) || quantity <= 0) invalid('quantity')
  return Object.fromEntries(Object.entries(nutrition).map(([key, value]) => [key, value * quantity])) as Nutrition
}

export const roundForDisplay = (value: number): number => Math.round(value)

// favoriteFoodIds sorts favorites first (stable, so relative order within each
// group — including any name/relevance ordering the caller already applied —
// is preserved).
export function searchFoods(foods: Food[], query: string, favoriteFoodIds?: readonly string[]): Food[] {
  const needle = query.trim().toLocaleLowerCase()
  const matches = !needle
    ? foods
    : foods.filter(
        (food) =>
          Object.values(food.name).some((value) => value.toLocaleLowerCase().includes(needle)) ||
          (food.description ?? '').toLocaleLowerCase().includes(needle),
      )
  if (!favoriteFoodIds?.length) return matches
  const favorites = new Set(favoriteFoodIds)
  return matches.toSorted((a, b) => Number(favorites.has(b.id)) - Number(favorites.has(a.id)))
}

export function toggleFavoriteFood(data: AppData, id: string): AppData {
  if (!data.foods.some((food) => food.id === id)) invalid('food not found')
  const favorites = new Set(data.favoriteFoodIds ?? [])
  favorites.has(id) ? favorites.delete(id) : favorites.add(id)
  return { ...copy(data), favoriteFoodIds: [...favorites] }
}

export function createMealEntry(input: Omit<MealEntry, 'id' | 'nutrition'> & { id?: string }, food: Food): MealEntry {
  const entry = {
    ...input,
    id: input.id ?? crypto.randomUUID(),
    nutrition: scaleNutrition(food.nutrition, input.quantity),
  }
  validateMealEntry(entry, [food])
  return copy(entry)
}

export function createTemporaryMealEntry(
  input: Omit<MealEntry, 'id' | 'foodId' | 'nutrition'> & { id?: string; foodName: string; nutrition: Nutrition },
): MealEntry {
  const entry = {
    ...input,
    id: input.id ?? crypto.randomUUID(),
    foodId: '',
  }
  validateMealEntry(entry, [])
  return copy(entry)
}

export function updateFood(data: AppData, id: string, changes: Partial<Omit<Food, 'id' | 'source'>>): AppData {
  const food = data.foods.find((item) => item.id === id)
  if (!food) invalid('food not found')
  if (food.source === 'bundled') invalid('bundled food is read-only')
  const next = { ...food, ...changes, updatedAt: new Date().toISOString() }
  validateFood(next)
  return { ...copy(data), foods: data.foods.map((item) => (item.id === id ? next : item)) }
}

export function deleteFood(data: AppData, id: string): AppData {
  const food = data.foods.find((item) => item.id === id)
  if (!food) invalid('food not found')
  if (food.source === 'bundled') invalid('bundled food is read-only')
  return { ...copy(data), foods: data.foods.filter((item) => item.id !== id) }
}

export function updateMealEntry(data: AppData, id: string, changes: Partial<Omit<MealEntry, 'id'>>): AppData {
  const entry = data.mealEntries.find((item) => item.id === id)
  if (!entry) invalid('meal entry not found')
  const next = { ...entry, ...changes }
  if (next.foodId === '') {
    validateMealEntry(next, [])
    return { ...copy(data), mealEntries: data.mealEntries.map((item) => (item.id === id ? copy(next) : item)) }
  }
  const food = data.foods.find((item) => item.id === next.foodId)
  if (!food) invalid('food not found')
  const updated = createMealEntry(next, food)
  return { ...copy(data), mealEntries: data.mealEntries.map((item) => (item.id === id ? updated : item)) }
}

export function deleteMealEntry(data: AppData, id: string): AppData {
  if (!data.mealEntries.some((item) => item.id === id)) invalid('meal entry not found')
  return { ...copy(data), mealEntries: data.mealEntries.filter((item) => item.id !== id) }
}

export function dailyTotals(data: AppData, date: string): Nutrition {
  return data.mealEntries
    .filter((entry) => entry.date === date)
    .reduce(
      (total, entry) => ({
        calories: total.calories + entry.nutrition.calories,
        protein: total.protein + entry.nutrition.protein,
        fat: total.fat + entry.nutrition.fat,
        carbohydrates: total.carbohydrates + entry.nutrition.carbohydrates,
      }),
      { calories: 0, protein: 0, fat: 0, carbohydrates: 0 },
    )
}

export type ThemePreference = 'light' | 'dark' | 'system'

export function resolveDarkMode(preference: ThemePreference, systemPrefersDark: boolean): boolean {
  return preference === 'system' ? systemPrefersDark : preference === 'dark'
}

export type CalorieTone = 'empty' | 'unavailable' | 'under' | 'on-target' | 'over'

export function calorieTone(dayCalories: number, targetCalories: number): CalorieTone {
  if (dayCalories === 0) return 'empty'
  if (targetCalories === 0) return 'unavailable'
  const ratio = dayCalories / targetCalories
  return ratio <= 1 ? 'on-target' : 'over'
}

const ACTIVITY_MULTIPLIERS = {
  bmrOnly: 1,
  sedentary: 1.2,
  light: 1.375,
  moderate: 1.55,
  very: 1.725,
  extra: 1.9,
} as const

export function validateProfile(profile: unknown): asserts profile is Profile {
  if (typeof profile !== 'object' || profile === null) invalid('profile')
  const value = profile as Record<string, unknown>
  if (
    typeof value.age !== 'number' ||
    !Number.isInteger(value.age) ||
    value.age < 1 ||
    value.age > 120 ||
    (value.sex !== 'female' && value.sex !== 'male') ||
    typeof value.heightCm !== 'number' ||
    !Number.isFinite(value.heightCm) ||
    value.heightCm < 50 ||
    value.heightCm > 250 ||
    typeof value.weightKg !== 'number' ||
    !Number.isFinite(value.weightKg) ||
    value.weightKg < 10 ||
    value.weightKg > 500 ||
    typeof value.activity !== 'string' ||
    !(value.activity in ACTIVITY_MULTIPLIERS) ||
    typeof value.targetWeightKg !== 'number' ||
    !Number.isFinite(value.targetWeightKg) ||
    value.targetWeightKg < 10 ||
    value.targetWeightKg > 500 ||
    typeof value.targetDate !== 'string' ||
    !/^\d{4}-\d{2}-\d{2}$/.test(value.targetDate)
  )
    invalid('profile')
}

export function estimateMaintenanceCalories(profile: Profile): number {
  return Math.round(estimateBMR(profile) * ACTIVITY_MULTIPLIERS[profile.activity])
}

export function estimateBMR(profile: Profile): number {
  validateProfile(profile)
  const bmr = 10 * profile.weightKg + 6.25 * profile.heightCm - 5 * profile.age + (profile.sex === 'male' ? 5 : -161)
  return Math.round(bmr)
}

export function estimateTargets(profile: Profile, fromDate = new Date().toISOString().slice(0, 10)): Nutrition {
  const days = (Date.parse(`${profile.targetDate}T00:00:00Z`) - Date.parse(`${fromDate}T00:00:00Z`)) / 86_400_000
  if (!Number.isFinite(days) || days <= 0) invalid('target date')
  const calories = Math.round(
    estimateMaintenanceCalories(profile) + ((profile.targetWeightKg - profile.weightKg) * 7700) / days,
  )
  const protein = Math.round(profile.targetWeightKg * 1.6 * 10) / 10
  const fat = Math.round(((calories * 0.25) / 9) * 10) / 10
  const carbohydrates = Math.round(((calories - protein * 4 - fat * 9) / 4) * 10) / 10
  return { calories, protein, fat, carbohydrates }
}

const LEGACY_TARGET_EFFECTIVE_FROM = '0001-01-01'

function targetPeriodsFor(data: AppData): TargetPeriod[] {
  if (data.targetPeriods?.length) return data.targetPeriods
  if (!data.profile) return []
  try {
    return [{ effectiveFrom: LEGACY_TARGET_EFFECTIVE_FROM, targets: resolveTargets(data.profile, data.targetOverrides) }]
  } catch {
    return []
  }
}

export function targetsForDate(data: AppData, date: string): Nutrition | null {
  return targetPeriodsFor(data)
    .filter((period) => period.effectiveFrom <= date)
    .sort((left, right) => left.effectiveFrom.localeCompare(right.effectiveFrom))
    .at(-1)?.targets ?? null
}

export function exerciseCaloriesForDate(data: AppData, date: string): number {
  return data.exerciseCalories?.[date] ?? 0
}

export function calorieTargetForDate(data: AppData, date: string): number {
  const targets = targetsForDate(data, date)
  return targets ? targets.calories + exerciseCaloriesForDate(data, date) : 0
}

export function setExerciseCalories(data: AppData, date: string, calories: number): AppData {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || !Number.isFinite(calories) || calories < 0) invalid('exercise calories')
  return { ...copy(data), exerciseCalories: { ...data.exerciseCalories, [date]: calories } }
}

export function setTargetPeriod(data: AppData, targets: Nutrition, effectiveFrom: string): AppData {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(effectiveFrom) || !validNutrition(targets)) invalid('target period')
  const targetPeriods = [...targetPeriodsFor(data).filter((period) => period.effectiveFrom !== effectiveFrom), { effectiveFrom, targets: copy(targets) }]
    .sort((left, right) => left.effectiveFrom.localeCompare(right.effectiveFrom))
  return { ...copy(data), targetPeriods }
}

function validateTargetOverrides(overrides: unknown): asserts overrides is TargetOverrides {
  if (typeof overrides !== 'object' || overrides === null) invalid('target overrides')
  for (const [key, value] of Object.entries(overrides)) {
    if (
      !['calories', 'protein', 'fat', 'carbohydrates'].includes(key) ||
      typeof value !== 'number' ||
      !Number.isFinite(value) ||
      value < 0
    )
      invalid('target override')
  }
}

type AchievementStats = {
  hasResolvedTargets: boolean
  recordedMeals: number
  temporaryEntries: number
  activeDays: number
  longestOnTargetRun: number
  maxIdentifiedFoodEntries: number
  uniqueIdentifiedFoods: number
  customFoods: number
}

function toDateStamp(iso: string): number {
  return Date.parse(`${iso}T00:00:00Z`)
}

function longestOnTargetRun(data: AppData): number {
  const dates = [...new Set(data.mealEntries.map((entry) => entry.date))].sort()
  let longest = 0
  let current = 0
  let previousDate = ''
  for (const date of dates) {
    const targetCalories = calorieTargetForDate(data, date)
    if (calorieTone(dailyTotals(data, date).calories, targetCalories) !== 'on-target') {
      current = 0
      previousDate = date
      continue
    }
    current = previousDate && toDateStamp(date) - toDateStamp(previousDate) === 86_400_000 ? current + 1 : 1
    previousDate = date
    longest = Math.max(longest, current)
  }
  return longest
}

function achievementStats(data: AppData, asOfDate: string): AchievementStats {
  const identifiedEntries = data.mealEntries.filter((entry) => entry.foodId !== '')
  const countsByFoodId = identifiedEntries.reduce((counts, entry) => {
    counts.set(entry.foodId, (counts.get(entry.foodId) ?? 0) + 1)
    return counts
  }, new Map<string, number>())
  return {
    hasResolvedTargets: targetsForDate(data, asOfDate) !== null,
    recordedMeals: data.mealEntries.length,
    temporaryEntries: data.mealEntries.filter((entry) => entry.foodId === '').length,
    activeDays: new Set(data.mealEntries.map((entry) => entry.date)).size,
    longestOnTargetRun: longestOnTargetRun(data),
    maxIdentifiedFoodEntries: Math.max(0, ...countsByFoodId.values()),
    uniqueIdentifiedFoods: countsByFoodId.size,
    customFoods: data.foods.filter((food) => food.source === 'user').length,
  }
}

export const achievementDefinitions: AchievementDefinition[] = [
    {
      id: 'ready-set',
      titleKey: 'achievementReadySetTitle',
      ruleKey: 'achievementReadySetRule',
      badgeNumber: '1',
      badgeIcon: 'crown',
      qualifies: (_, stats) => stats.hasResolvedTargets,
    },
    {
      id: 'first-plate',
      titleKey: 'achievementFirstPlateTitle',
      ruleKey: 'achievementFirstPlateRule',
      badgeNumber: '1',
      badgeIcon: 'star',
      qualifies: (_, stats) => stats.recordedMeals >= 1,
    },
    {
      id: 'tenfold-log',
      titleKey: 'achievementTenfoldLogTitle',
      ruleKey: 'achievementTenfoldLogRule',
      badgeNumber: '10',
      badgeIcon: 'star',
      qualifies: (_, stats) => stats.recordedMeals >= 10,
    },
    {
      id: 'fifty-plates',
      titleKey: 'achievementFiftyPlatesTitle',
      ruleKey: 'achievementFiftyPlatesRule',
      badgeNumber: '50',
      badgeIcon: 'crown',
      qualifies: (_, stats) => stats.recordedMeals >= 50,
    },
    {
      id: 'hundred-plates',
      titleKey: 'achievementHundredPlatesTitle',
      ruleKey: 'achievementHundredPlatesRule',
      badgeNumber: '100',
      badgeIcon: 'crown',
      qualifies: (_, stats) => stats.recordedMeals >= 100,
    },
    {
      id: 'quick-start',
      titleKey: 'achievementQuickStartTitle',
      ruleKey: 'achievementQuickStartRule',
      badgeNumber: '5',
      badgeIcon: 'star',
      qualifies: (_, stats) => stats.temporaryEntries >= 5,
    },
    {
      id: 'three-day-start',
      titleKey: 'achievementThreeDayStartTitle',
      ruleKey: 'achievementThreeDayStartRule',
      badgeNumber: '3',
      badgeIcon: 'star',
      qualifies: (_, stats) => stats.activeDays >= 3,
    },
    {
      id: 'week-witness',
      titleKey: 'achievementWeekWitnessTitle',
      ruleKey: 'achievementWeekWitnessRule',
      badgeNumber: '7',
      badgeIcon: 'star',
      qualifies: (_, stats) => stats.activeDays >= 7,
    },
    {
      id: 'monthly-companion',
      titleKey: 'achievementMonthlyCompanionTitle',
      ruleKey: 'achievementMonthlyCompanionRule',
      badgeNumber: '30',
      badgeIcon: 'crown',
      qualifies: (_, stats) => stats.activeDays >= 30,
    },
    {
      id: 'hundred-day-journal',
      titleKey: 'achievementHundredDayJournalTitle',
      ruleKey: 'achievementHundredDayJournalRule',
      badgeNumber: '100',
      badgeIcon: 'crown',
      qualifies: (_, stats) => stats.activeDays >= 100,
    },
    {
      id: 'steady-starter',
      titleKey: 'achievementSteadyStarterTitle',
      ruleKey: 'achievementSteadyStarterRule',
      badgeNumber: '3',
      badgeIcon: 'star',
      qualifies: (_, stats) => stats.longestOnTargetRun >= 3,
    },
    {
      id: 'seven-day-rhythm',
      titleKey: 'achievementSevenDayRhythmTitle',
      ruleKey: 'achievementSevenDayRhythmRule',
      badgeNumber: '7',
      badgeIcon: 'star',
      qualifies: (_, stats) => stats.longestOnTargetRun >= 7,
    },
    {
      id: 'two-week-pace',
      titleKey: 'achievementTwoWeekPaceTitle',
      ruleKey: 'achievementTwoWeekPaceRule',
      badgeNumber: '14',
      badgeIcon: 'crown',
      qualifies: (_, stats) => stats.longestOnTargetRun >= 14,
    },
    {
      id: 'monthly-rhythm',
      titleKey: 'achievementMonthlyRhythmTitle',
      ruleKey: 'achievementMonthlyRhythmRule',
      badgeNumber: '30',
      badgeIcon: 'crown',
      qualifies: (_, stats) => stats.longestOnTargetRun >= 30,
    },
    {
      id: 'familiar-favorite',
      titleKey: 'achievementFamiliarFavoriteTitle',
      ruleKey: 'achievementFamiliarFavoriteRule',
      badgeNumber: '10',
      badgeIcon: 'star',
      qualifies: (_, stats) => stats.maxIdentifiedFoodEntries >= 10,
    },
    {
      id: 'regular',
      titleKey: 'achievementRegularTitle',
      ruleKey: 'achievementRegularRule',
      badgeNumber: '25',
      badgeIcon: 'crown',
      qualifies: (_, stats) => stats.maxIdentifiedFoodEntries >= 25,
    },
    {
      id: 'signature-order',
      titleKey: 'achievementSignatureOrderTitle',
      ruleKey: 'achievementSignatureOrderRule',
      badgeNumber: '50',
      badgeIcon: 'crown',
      qualifies: (_, stats) => stats.maxIdentifiedFoodEntries >= 50,
    },
    {
      id: 'ten-tastes',
      titleKey: 'achievementTenTastesTitle',
      ruleKey: 'achievementTenTastesRule',
      badgeNumber: '10',
      badgeIcon: 'star',
      qualifies: (_, stats) => stats.uniqueIdentifiedFoods >= 10,
    },
    {
      id: 'twenty-five-tastes',
      titleKey: 'achievementTwentyFiveTastesTitle',
      ruleKey: 'achievementTwentyFiveTastesRule',
      badgeNumber: '25',
      badgeIcon: 'crown',
      qualifies: (_, stats) => stats.uniqueIdentifiedFoods >= 25,
    },
    {
      id: 'fifty-tastes',
      titleKey: 'achievementFiftyTastesTitle',
      ruleKey: 'achievementFiftyTastesRule',
      badgeNumber: '50',
      badgeIcon: 'crown',
      qualifies: (_, stats) => stats.uniqueIdentifiedFoods >= 50,
    },
    {
      id: 'first-custom-food',
      titleKey: 'achievementFirstCustomFoodTitle',
      ruleKey: 'achievementFirstCustomFoodRule',
      badgeNumber: '1',
      badgeIcon: 'star',
      qualifies: (_, stats) => stats.customFoods >= 1,
    },
    {
      id: 'personal-pantry',
      titleKey: 'achievementPersonalPantryTitle',
      ruleKey: 'achievementPersonalPantryRule',
      badgeNumber: '5',
      badgeIcon: 'crown',
      qualifies: (_, stats) => stats.customFoods >= 5,
    },
]

export function resolveTargets(
  profile: Profile,
  overrides: TargetOverrides = {},
  fromDate = new Date().toISOString().slice(0, 10),
): Nutrition {
  const estimated = estimateTargets(profile, fromDate)
  validateTargetOverrides(overrides)
  return { ...estimated, ...overrides }
}

function checkedData(data: AppData): AppData {
  validateAppData(data)
  return copy(data)
}

function migrateTargetPeriods(data: AppData): AppData {
  if (data.targetPeriods !== undefined || !data.profile) return data
  const targetPeriods = targetPeriodsFor(data)
  return targetPeriods.length ? { ...data, targetPeriods } : data
}

function withAchievements(data: AppData, achievements: AchievementRecord[]): AppData {
  if (achievements.length === 0 && data.achievements === undefined) return data
  return { ...data, achievements }
}

export function evaluateAchievements(data: AppData, now = new Date().toISOString()): AppData {
  const next = migrateTargetPeriods(checkedData(data))
  const existing = new Map((next.achievements ?? []).map((record) => [record.id, record]))
  const stats = achievementStats(next, now.slice(0, 10))
  const unlocked = achievementDefinitions
    .filter((definition) => !existing.has(definition.id) && definition.qualifies(next, stats))
    .map((definition) => ({ id: definition.id, unlockedAt: now }))
  if (unlocked.length === 0) return next
  return withAchievements(next, [...(next.achievements ?? []), ...unlocked])
}

export function markAchievementsRead(data: AppData, now = new Date().toISOString()): AppData {
  const next = checkedData(data)
  const achievements = next.achievements?.map((record) => (record.readAt ? record : { ...record, readAt: now })) ?? []
  if (achievements.every((record, index) => record.readAt === next.achievements?.[index]?.readAt)) return next
  return withAchievements(next, achievements)
}

export function prepareAppData(data: AppData, now = new Date().toISOString()): AppData {
  return evaluateAchievements(migrateTargetPeriods(checkedData(data)), now)
}

function mergeData(current: AppData, imported: AppData): AppData {
  const mergeById = <T extends { id: string }>(existing: T[], incoming: T[]) => {
    const merged = new Map(existing.map((item) => [item.id, item]))
    incoming.forEach((item) => merged.set(item.id, item))
    return [...merged.values()]
  }
  return {
    foods: mergeById(current.foods, imported.foods),
    mealEntries: mergeById(current.mealEntries, imported.mealEntries),
    ...(current.exerciseCalories || imported.exerciseCalories
      ? { exerciseCalories: { ...current.exerciseCalories, ...imported.exerciseCalories } }
      : {}),
    ...(current.profile || imported.profile ? { profile: imported.profile ?? current.profile } : {}),
    ...(current.targetOverrides || imported.targetOverrides
      ? { targetOverrides: imported.targetOverrides ?? current.targetOverrides }
      : {}),
    ...(current.targetPeriods || imported.targetPeriods
      ? {
          targetPeriods: [
            ...new Map(
              [...(current.targetPeriods ?? []), ...(imported.targetPeriods ?? [])].map((period) => [
                period.effectiveFrom,
                period,
              ]),
            ).values(),
          ].sort((left, right) => left.effectiveFrom.localeCompare(right.effectiveFrom)),
        }
      : {}),
    ...(current.achievements || imported.achievements
      ? { achievements: mergeById(current.achievements ?? [], imported.achievements ?? []) }
      : {}),
    ...(current.favoriteFoodIds || imported.favoriteFoodIds
      ? { favoriteFoodIds: [...new Set([...(current.favoriteFoodIds ?? []), ...(imported.favoriteFoodIds ?? [])])] }
      : {}),
  }
}

export function previewBackup(file: string): ImportResult {
  try {
    const parsed: unknown = JSON.parse(file)
    if (
      typeof parsed !== 'object' ||
      parsed === null ||
      !('schemaVersion' in parsed) ||
      parsed.schemaVersion !== SCHEMA_VERSION ||
      !('data' in parsed)
    )
      throw new Error('Unsupported backup version')
    const imported = (parsed as { data: unknown }).data
    validateAppData(imported)
    return { schemaVersion: SCHEMA_VERSION, data: copy(imported) }
  } catch (error) {
    throw new Error(`Invalid backup: ${error instanceof Error ? error.message : 'Unknown error'}`)
  }
}

export function createMemoryStore(initial: AppData = emptyData()): Store {
  let data = checkedData(initial)

  return {
    async load() {
      data = prepareAppData(data)
      return copy(data)
    },
    async save(next) {
      data = prepareAppData(next)
    },
    async export() {
      return JSON.stringify({ schemaVersion: SCHEMA_VERSION, exportedAt: new Date().toISOString(), data })
    },
    async import(file) {
      const imported = previewBackup(file)
      data = prepareAppData(mergeData(data, imported.data))
      return { schemaVersion: SCHEMA_VERSION, data: copy(data) }
    },
  }
}
